Add support for custom reponse on validation failure
123inkt/symfony-request-validation pull request #21
Opened 2022-08-26 19:01 UTC by frankdekker

2022-08-26 19:16 UTC, frankdekker commented
@bram123 I'm rethinking the way we should return the response to have a more natural flow when creating the Validated request. Overriding the handleViolations method doesn't quite fit. Maybe do a brainstorm next week.

2022-09-07 10:57 UTC, bram123 requested changes

2022-09-07 10:57 UTC, bram123 commented on src/AbstractValidatedRequest.php
>      abstract protected function getValidationRules(): ValidationRules;
@frankdekker 
Can we make this methode return ?ValidationRules? And handle that in validate().
For cases where we only need to do custom validation, and no request-structure validation.

2022-09-09 12:40 UTC, bram123 approved these changes

2022-09-09 13:51 UTC, merged